### ISSUE TITLE
it don't appears [Bug] <title>

### ISSUE THREAD

**Issue by aliv3zoka** [DaBluLite/DiscordColorways#5]
### Discord Account

aliv3zoka

### Client Mod

betterdiscord

### What happens when the bug or crash occurs?

don't appear 

### What is the expected behaviour?

appear the feature

### How do you recreate this bug or crash?

i downloaded the plugin and placed it on the plugins folder and then enable it and doesn't work

### Errors

```
no errors
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by OrganizedSchizo** [comment]
TypeError: Cannot read properties of undefined (reading 'colorways')
    at eval (betterdiscord://plugins/DiscordColorways.plugin.js:5068:53)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201


I get this error when I try to compile to my discord via plugins folder

**Comment by blankyblank** [comment]
I'm having the same issue. It's funny because I actually managed to get it to work initially. then when I set the color way to grey for virtualboy, they text wasn't really readable. and none of the other colorsways were showing up anymore. So i deleted it, and tried to add it again, then I ran into this.

**Comment by DaBluLite** [comment]
Sorry for the late response. I have fixed the issue with custom colorways and the such. The server list button is still a mess, so I will have to find a new way to patch it. There are also some issues with the info modal that I will get to soon.

**Comment by DaBluLite** [comment]
My last message was in response to the other 2 comments. If there are any other issues, please report them properly. This thread will be closed due to not following the bug report guidelines.
