### ISSUE TITLE
[Bug] vencord settings patch no effect

### ISSUE THREAD

**Issue by verticalsync** [DaBluLite/DiscordColorways#6]
### Client Mod

Vencord

### What happens when the bug or crash occurs?

The settings code has changed alot so the patch is now not gonna work

`/\{section:(\i\.\i)\.HEADER,\s*label:(\i)\.\i\.Messages\.APP_SETTINGS\}/ `

### What is the expected behaviour?

For the settings to pop up.

### How do you recreate this bug or crash?

Use the plugin

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by DaBluLite** [comment]
Yes, I'm aware that this patch is no longer working. I will push a fix

**Comment by DaBluLite** [comment]
Version 5.7.0 Beta 1 has been released, resolving the issue

**Comment by verticalsync** [comment]
> Version 5.7.0 Beta 1 has been released, resolving the issue

Where has it been released?
