### ISSUE TITLE
[Bug] <title>

### ISSUE THREAD

**Issue by silverhandsan** [DaBluLite/DiscordColorways#7]
### Client Mod

Vencord

### What happens when the bug or crash occurs?

when clicking the "Download the Vencord userplugin" link, it goes to a error 404 page.

### What is the expected behaviour?

not sure

### How do you recreate this bug or crash?

click on the download the vencord userplugin link

browser: opera gx

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by DaBluLite** [comment]
Please sook again at the readme
